name: Installation Check

'on':
  workflow_dispatch:
  # schedule:
  #   - cron: "0 6 * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upgrade PIP + Setuptools
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools

      - name: Install TidyPy
        run: pip install tidypy

